steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/free-trail-458302/new-test/frontend:$SHORT_SHA', '.']

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/free-trail-458302/new-test/frontend:$SHORT_SHA']

  # Clone helm repo and update tag in values.yaml
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: bash
    args:
      - -c
      - |
        GITHUB_TOKEN=$(gcloud secrets versions access latest --secret=github-token)
        git config --global user.email "ci@cloudbuild.gcp"
        git config --global user.name "cloud-build"
        git clone https://paras0109:${GITHUB_TOKEN}@github.com/paras0109/helm-deploy-repo.git
        cd helm-deploy-repo
        sed -i "s/tag: .*/tag: \"$SHORT_SHA\"/" values.yaml
        git add values.yaml
        git commit -m "Update image tag to $SHORT_SHA"
        git push origin main

images:
  - us-central1-docker.pkg.dev/free-trail-458302/new-test/frontend:$SHORT_SHA
