  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    secretEnv: ['GITHUB_TOKEN']
    args:
      - -c
      - |
        git config --global user.email "paras.n0109@gmail.com"
        git config --global user.name "paras0109"
        git clone https://paras0109:${GITHUB_TOKEN}@github.com/paras0109/helm-deploy-repo.git
        cd helm-deploy-repo
        sed -i "s/tag: .*/tag: \"${_IMAGE_TAG}\"/" values.yaml
        git add values.yaml
        git commit -m "Update image tag to ${_IMAGE_TAG}"
        git push origin main
