steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        GITHUB_TOKEN=$(gcloud secrets versions access latest --secret=github-token)
        echo "Fetched GitHub token
        
