steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/free-trail-458302/new-test/frontend:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/free-trail-458302/new-test/frontend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git config --global user.email "ci@build.com"
        git config --global user.name "cloud-build"
        git clone https://github.com/paras0109/helm-deploy-repo.git
        cd helm-deploy-repo/frontend
        sed -i "s/tag: .*/tag: \"$SHORT_SHA\"/" values.yaml
        git commit -am "Update image tag to $SHORT_SHA"
        git push https://$(cat /secrets/github-token)@github.com/paras0109/helm-deploy-repo.git HEAD:main
    secretEnv: ['GITHUB_TOKEN']

secrets:
- kmsKeyName: projects/free-trail-458302/locations/global/keyRings/my-keyring/cryptoKeys/my-key  # optional if you're using CMEK
  secretEnv:
    GITHUB_TOKEN: projects/free-trail-458302/secrets/github-token/versions/latest

images:
  - 'us-central1-docker.pkg.dev/free-trail-458302/new-test/frontend:$SHORT_SHA'
