options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
  machineType: E2_SMALL

serviceAccount: ci-cd-service-account@free-trail-458302.iam.gserviceaccount.com

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        echo "Fetching secret..."
        gcloud secrets versions access latest --secret=github-token
